e1: equ 5
SECTION TEXT
if e1
stop
INPUT OLD_DATA+2 ;arositneaorisntoo enaorisntarstarst
LOAD OLD_DATA ; aorisentoiarnst
L1: DIV DOIS
STORE NEW_DATA
MUL DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA,OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS: CONST e1
OLD_DATA: SPACE e1
NEW_DATA: SPACE
TMP_DATA: SPACE